# Chinese (Simplified) distribution defaults

[global]
app_mode = 0             # 0=Normal, 1=Borderless, 2=Mini
append_logs = false
dialog_fade_enabled = true
dialog_fade_timeout = 20.0
ui_language = "zh-CN"   # UI language: en or zh-CN
ui_scale = 1.0

[global.translation]
target_lang = "zh-cn"    # en-us, zh-cn, zh-tw