# English distribution defaults

[global]
app_mode = 0             # 0=Normal, 1=Borderless, 2=Mini
append_logs = false
dialog_fade_enabled = true
dialog_fade_timeout = 20.0
ui_language = "en"       # UI language: en or zh-CN
ui_scale = 1.0

[global.translation]
auto_apply_changes = false
target_lang = "en-us"    # en-us, zh-cn, zh-tw
translate_enabled = false # start disabled; enable in UI when ready
translation_backend = 0   # 0=OpenAI, 1=Google, 2=Zhipu, 3=Qwen-MT, 4=Niutrans
