function(configure_windows_resources target)
  if(NOT WIN32)
    return()
  endif()

  set(DQX_APP_ASSET_DIR "${CMAKE_SOURCE_DIR}/assets")
  file(TO_CMAKE_PATH "${DQX_APP_ASSET_DIR}" DQX_APP_ASSET_DIR)

  set(DQX_APP_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
  if(DQX_APP_VERSION_MAJOR STREQUAL "")
    set(DQX_APP_VERSION_MAJOR 0)
  endif()
  
  set(DQX_APP_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
  if(DQX_APP_VERSION_MINOR STREQUAL "")
    set(DQX_APP_VERSION_MINOR 0)
  endif()
  
  set(DQX_APP_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
  if(DQX_APP_VERSION_PATCH STREQUAL "")
    set(DQX_APP_VERSION_PATCH 0)
  endif()
  
  set(DQX_APP_VERSION_TWEAK "${PROJECT_VERSION_TWEAK}")
  if(DQX_APP_VERSION_TWEAK STREQUAL "")
    set(DQX_APP_VERSION_TWEAK 0)
  endif()

  set(APP_VERSION_COMMA "${DQX_APP_VERSION_MAJOR},${DQX_APP_VERSION_MINOR},${DQX_APP_VERSION_PATCH},${DQX_APP_VERSION_TWEAK}")
  set(APP_VERSION_STRING "${DQX_APP_VERSION_MAJOR}.${DQX_APP_VERSION_MINOR}.${DQX_APP_VERSION_PATCH}.${DQX_APP_VERSION_TWEAK}")
  set(ASSET_DIR "${DQX_APP_ASSET_DIR}")

  configure_file(
    ${CMAKE_SOURCE_DIR}/src/app/app.rc.in
    ${CMAKE_BINARY_DIR}/app.rc
    @ONLY
  )

  target_sources(${target} PRIVATE ${CMAKE_BINARY_DIR}/app.rc)
  
  unset(ASSET_DIR)
endfunction()